#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

# cleanCase0

# rm -rf *.dat 
# rm -rf *.png

rm -rf PyFoam*

rm -rf cases/*

rm -rf ax_result_data/html/*.html

rm ax_result_data/*

# -----------------------------------------------------------------------------
