#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# Usage- ./Allrun <grid_level>

./Allclean # Redundant but safe

restore0Dir

./copyGrid.sh ${1} 2d

plot3dToFoam -2D 1 -noBlank backstep5_${1}levdn.p2dfmt

autoPatch -overwrite 90

topoSet

createPatch -overwrite

createPatch -dict system/patchMerge -overwrite

runApplication simpleFoam

postProcess -funcs '(magU sample)' -latestTime

cp -r postProcessing/sample/2000/* ValidationData/post_data/grids/grid_${1}/

#------------------------------------------------------------------------------
