#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

plot3dToFoam -2D 1 -noBlank backstep5_4levdn.p2dfmt

autoPatch -overwrite 90

topoSet

createPatch -overwrite

createPatch -dict system/patchMerge -overwrite

runApplication simpleFoam

postProcess -funcs '(magU sample)' -latestTime

#------------------------------------------------------------------------------
